import jsPDF from "jspdf";
import type { ResumeVersion } from "@/hooks/useResumeVersions";

/**
 * Export a resume version using the consistent professional template.
 * Template order: Name & Contact → Summary → Skills → Experience → Projects → Education
 */
export const exportVersionAsPdf = (version: ResumeVersion) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 18;
  const contentWidth = pageWidth - margin * 2;
  let y = 18;

  // Colors
  const colorPrimary: [number, number, number] = [79, 70, 229];
  const colorDark: [number, number, number] = [17, 24, 39];
  const colorGray: [number, number, number] = [107, 114, 128];
  const colorLightGray: [number, number, number] = [156, 163, 175];

  const checkPageBreak = (needed: number) => {
    if (y + needed > pageHeight - 20) {
      doc.addPage();
      y = 18;
    }
  };

  const addText = (
    text: string,
    size: number,
    style: "normal" | "bold" = "normal",
    color: [number, number, number] = colorDark
  ) => {
    doc.setFontSize(size);
    doc.setFont("helvetica", style);
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(text, contentWidth);
    const lineHeight = size * 0.45;
    checkPageBreak(lines.length * lineHeight + 4);
    doc.text(lines, margin, y);
    y += lines.length * lineHeight + 2;
  };

  const addSectionDivider = (title: string) => {
    y += 5;
    checkPageBreak(14);
    doc.setDrawColor(...colorPrimary);
    doc.setLineWidth(0.6);
    doc.line(margin, y, pageWidth - margin, y);
    y += 5;
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...colorPrimary);
    doc.text(title.toUpperCase(), margin, y);
    y += 6;
  };

  // ═══ 1. NAME & CONTACT ═══
  const profileName = version.profile_data?.name || "Candidate";
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...colorDark);
  doc.text(profileName, margin, y);
  y += 8;

  // Target info
  if (version.target_job_title) {
    const targetText = version.target_company
      ? `Optimized for: ${version.target_job_title} at ${version.target_company}`
      : `Optimized for: ${version.target_job_title}`;
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...colorGray);
    doc.text(targetText, margin, y);
    y += 4;
  }

  // ═══ 2. SUMMARY ═══
  const summary = version.optimized_summary || version.profile_data?.tagline || "";
  if (summary) {
    addSectionDivider("Professional Summary");
    addText(summary, 10);
  }

  // ═══ 3. SKILLS ═══
  if (version.optimized_skills.length > 0) {
    addSectionDivider("Skills");
    const skillText = version.optimized_skills.join("  \u2022  ");
    addText(skillText, 9.5);
  }

  // ═══ 4. EXPERIENCE ═══
  if (version.optimized_bullet_points.length > 0) {
    addSectionDivider("Experience");
    version.optimized_bullet_points.forEach((bp) => {
      const bullet = bp.optimized || bp.original;
      if (!bullet.trim()) return;
      const bulletText = `\u2022  ${bullet}`;
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...colorDark);
      const lines = doc.splitTextToSize(bulletText, contentWidth - 4);
      checkPageBreak(lines.length * 4.5 + 2);
      doc.text(lines, margin + 2, y);
      y += lines.length * 4.2 + 1.5;
    });
  }

  // ═══ 5. PROJECTS ═══
  // (projects from profile data if available)

  // ═══ 6. EDUCATION ═══
  if (version.profile_data?.education) {
    addSectionDivider("Education");
    addText(version.profile_data.education, 10);
  }

  // Experience summary from profile
  if (version.profile_data?.experience) {
    addSectionDivider("Experience Summary");
    addText(version.profile_data.experience, 10);
  }

  // ── Footer ──
  doc.setFontSize(7);
  doc.setTextColor(...colorLightGray);
  doc.text("Generated by Career Intelligence Platform", margin, pageHeight - 10);

  if (version.application_strength != null) {
    const scoreText = `Match Score: ${version.application_strength}/100`;
    const scoreWidth = doc.getTextWidth(scoreText);
    doc.text(scoreText, pageWidth - margin - scoreWidth, pageHeight - 10);
  }

  const fileName = `${profileName.replace(/\s+/g, "_")}_${version.name.replace(/\s+/g, "_")}.pdf`;
  doc.save(fileName);
};
