import jsPDF from "jspdf";
import type { ResumeOptimization, JobListing } from "@/types/jobs";
import type { AnalysisProfile } from "@/types/analysis";

export const exportOptimizedResume = (
  profile: AnalysisProfile | undefined,
  job: JobListing,
  optimization: ResumeOptimization
) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 20;

  const addText = (text: string, size: number, style: "normal" | "bold" = "normal", color: [number, number, number] = [30, 30, 30]) => {
    doc.setFontSize(size);
    doc.setFont("helvetica", style);
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(text, contentWidth);
    if (y + lines.length * (size * 0.5) > 275) {
      doc.addPage();
      y = 20;
    }
    doc.text(lines, margin, y);
    y += lines.length * (size * 0.45) + 2;
  };

  const addSectionHeader = (title: string) => {
    y += 4;
    doc.setDrawColor(99, 102, 241);
    doc.setLineWidth(0.5);
    doc.line(margin, y, pageWidth - margin, y);
    y += 6;
    addText(title.toUpperCase(), 11, "bold", [99, 102, 241]);
    y += 2;
  };

  // Header
  addText(profile?.name || "Candidate", 22, "bold", [17, 24, 39]);
  y += 1;
  addText(`Optimized for: ${job.title} at ${job.company}`, 10, "normal", [107, 114, 128]);
  y += 2;
  addText(`Application Strength: ${optimization.applicationStrength.score}/100`, 11, "bold", [99, 102, 241]);
  y += 4;

  // Summary
  addSectionHeader("Professional Summary");
  addText(optimization.optimizedSections.summary.optimized, 10);

  // Skills
  addSectionHeader("Skills");
  const skills = optimization.optimizedSections.skills.optimized;
  addText(skills.join("  •  "), 10);

  if (optimization.optimizedSections.skills.added.length > 0) {
    y += 2;
    addText("Suggested additions: " + optimization.optimizedSections.skills.added.join(", "), 9, "normal", [107, 114, 128]);
  }

  // Experience bullet points
  if (optimization.optimizedSections.bulletPoints.length > 0) {
    addSectionHeader("Experience (Optimized)");
    optimization.optimizedSections.bulletPoints.forEach((bp) => {
      addText(`• ${bp.optimized}`, 10);
      y += 1;
    });
  }

  // Relevant Projects
  if (optimization.optimizedSections.projects.length > 0) {
    addSectionHeader("Relevant Projects");
    optimization.optimizedSections.projects.forEach((proj) => {
      addText(proj.name, 10, "bold");
      addText(proj.highlight, 9, "normal", [55, 65, 81]);
      addText(`Relevance: ${proj.relevance}`, 8, "normal", [107, 114, 128]);
      y += 2;
    });
  }

  // Strong Areas
  addSectionHeader("Strengths for This Role");
  optimization.applicationStrength.strongAreas.forEach((s) => {
    addText(`✓ ${s}`, 10, "normal", [16, 185, 129]);
  });

  // Missing Skills
  if (optimization.missingSkills.length > 0) {
    addSectionHeader("Skills Gap & Learning Paths");
    optimization.missingSkills.forEach((ms) => {
      addText(`${ms.skill} (${ms.importance})`, 10, "bold");
      addText(ms.learningPath, 9, "normal", [107, 114, 128]);
      y += 2;
    });
  }

  // Footer
  y += 6;
  doc.setFontSize(7);
  doc.setTextColor(156, 163, 175);
  doc.text("Generated by AI Career Intelligence Platform", margin, 285);

  const fileName = `${(profile?.name || "Resume").replace(/\s+/g, "_")}_Optimized_${job.company.replace(/\s+/g, "_")}.pdf`;
  doc.save(fileName);
};
