import jsPDF from "jspdf";
import type { ResumeVersion } from "@/hooks/useResumeVersions";

export const exportVersionAsPdf = (version: ResumeVersion) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 20;

  const addText = (
    text: string,
    size: number,
    style: "normal" | "bold" = "normal",
    color: [number, number, number] = [30, 30, 30]
  ) => {
    doc.setFontSize(size);
    doc.setFont("helvetica", style);
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(text, contentWidth);
    if (y + lines.length * (size * 0.5) > 275) {
      doc.addPage();
      y = 20;
    }
    doc.text(lines, margin, y);
    y += lines.length * (size * 0.45) + 2;
  };

  const addSectionHeader = (title: string) => {
    y += 4;
    doc.setDrawColor(99, 102, 241);
    doc.setLineWidth(0.5);
    doc.line(margin, y, pageWidth - margin, y);
    y += 6;
    addText(title.toUpperCase(), 11, "bold", [99, 102, 241]);
    y += 2;
  };

  // Header - Name
  const profileName = version.profile_data?.name || "Candidate";
  addText(profileName, 22, "bold", [17, 24, 39]);
  y += 1;

  // Target info
  if (version.target_job_title) {
    const targetText = version.target_company
      ? `Optimized for: ${version.target_job_title} at ${version.target_company}`
      : `Optimized for: ${version.target_job_title}`;
    addText(targetText, 10, "normal", [107, 114, 128]);
    y += 1;
  }

  if (version.application_strength != null) {
    addText(`Application Strength: ${version.application_strength}/100`, 11, "bold", [99, 102, 241]);
    y += 4;
  }

  // Summary
  if (version.optimized_summary) {
    addSectionHeader("Professional Summary");
    addText(version.optimized_summary, 10);
  }

  // Skills
  if (version.optimized_skills.length > 0) {
    addSectionHeader("Skills");
    addText(version.optimized_skills.join("  •  "), 10);
  }

  // Experience
  if (version.optimized_bullet_points.length > 0) {
    addSectionHeader("Experience");
    version.optimized_bullet_points.forEach((bp) => {
      addText(`• ${bp.optimized || bp.original}`, 10);
      y += 1;
    });
  }

  // Education & Experience from profile_data
  if (version.profile_data?.education) {
    addSectionHeader("Education");
    addText(version.profile_data.education, 10);
  }

  if (version.profile_data?.experience) {
    addSectionHeader("Experience Summary");
    addText(version.profile_data.experience, 10);
  }

  // Footer
  y += 6;
  doc.setFontSize(7);
  doc.setTextColor(156, 163, 175);
  doc.text("Generated by AI Career Intelligence Platform", margin, 285);

  const fileName = `${profileName.replace(/\s+/g, "_")}_${version.name.replace(/\s+/g, "_")}.pdf`;
  doc.save(fileName);
};
